### ISSUE TITLE
Does wildcard work for CNAMES or not?

### ISSUE THREAD

**Issue by DiDHack** [Ranger802004/asusmerlin#53]
Hello!
I have installed dig. I tried to add *.youtube.com to the domain list.
Traceroute for www.youtube.com (CNAME youtube-ui.l.google.com) goes not through VPN gateway.
When I added exactly www.youtube.com to the list it catches CNAME of www.youtube.com

So log dnsmasq shows cnames too. Why don't catch it from this log? Or can we not be sure that next line is that we try to find?

```
Nov  9 19:09:14 dnsmasq[25588]: query[A] www.youtube.com from 192.168.1.2
Nov  9 19:09:14 dnsmasq[25588]: forwarded www.youtube.com to 192.168.50.1
Nov  9 19:09:14 dnsmasq[25588]: query[A] www.youtube.com from 192.168.1.2
Nov  9 19:09:14 dnsmasq[25588]: forwarded www.youtube.com to 8.8.8.8
Nov  9 19:09:14 dnsmasq[25588]: reply www.youtube.com is <CNAME>
Nov  9 19:09:14 dnsmasq[25588]: reply youtube-ui.l.google.com is <CNAME>
Nov  9 19:09:14 dnsmasq[25588]: reply wide-youtube.l.google.com is 173.194.220.198
Nov  9 19:09:14 dnsmasq[25588]: query[A] wide-youtube.l.google.com from 192.168.1.2
Nov  9 19:09:14 dnsmasq[25588]: cached wide-youtube.l.google.com is 173.194.220.198
Nov  9 19:09:14 dnsmasq[25588]: query[AAAA] wide-youtube.l.google.com from 192.168.1.2
Nov  9 19:09:14 dnsmasq[25588]: forwarded wide-youtube.l.google.com to 192.168.50.1
Nov  9 19:09:14 dnsmasq[25588]: query[AAAA] wide-youtube.l.google.com from 192.168.1.2
Nov  9 19:09:14 dnsmasq[25588]: forwarded wide-youtube.l.google.com to 8.8.8.8
Nov  9 19:09:14 dnsmasq[25588]: reply wide-youtube.l.google.com is 2a00:1450:400c:c0b::c6
```

**Comment by DiDHack** [comment]
We can use dig if we see in the log
```
reply www.youtube.com is <CNAME>
```

**Comment by Ranger802004** [comment]
Let me clarify a couple things here.  Dig will match CNAME records for full domains, not wildcards and only from lookups and not dnsmasq log.  Wildcards are only collected from dnsmasq or AdGuardHome logging.

**Comment by DiDHack** [comment]
Yes. But if I add *.youtube.com to the domain list. We can check the dnsmasq log for `reply www.youtube.com is <CNAME>` lines and then add this to the list automatically (if cnames is enabled) for the next cron job or we can check it with dig immediately and then add new IPs to the ip list.

**Comment by Ranger802004** [comment]
I will look into it and see if it is technically feasible.

**Comment by Gundabadec** [comment]
@Ranger802004 Script automatically added **ou** domain to random policy. 
```
14:21:24 domain_vpn_routing: Debug - CNAME: ou is already added to trackers
14:21:24 domain_vpn_routing: Debug - CNAME: ou is already added to trackers
14:21:24 domain_vpn_routing: Debug - CNAME: ou is already added to trackers
```

**Comment by Ranger802004** [comment]
Go ahead and remove it from the policy and if it comes back let me know.  There were some issues surrounding this problem in a previous version that were resolved in v3.0.1.

**Comment by Ranger802004** [comment]
I am doing some additional testing and I see where there can still be some erroneous data entering the policy, let me work to resolve that and release a fix.

**Comment by Gundabadec** [comment]
@Ranger802004 "I remove it every time, but it returns"
Sometimes `add DVR-youtube-v4 8.8.8.8 comment "ou,youtube.com"` in ipset file returns without `ou` line in `_domainlist`

**Comment by Ranger802004** [comment]
Do you have ou,youtube.com as a domain added in a policy?

**Comment by Gundabadec** [comment]
@Ranger802004 No. Just `youtube.com` now. But sometimes `ou` domain is added to policy domain list automatically, perhaps when running the `query policy` command. I have removed it manually, but the line like this: `add DVR-policyname-v4 8.8.8.8 comment “ou, real domain, real domain 2”` still appears in a random policy IP set.

**Comment by Ranger802004** [comment]
Did you remove it using the commands or manually deleting it from the domainlist file? If you are manually deleting it from the domainlist file readd it back and use the UI to remove it from the policy.

**Comment by Ranger802004** [comment]
v3.0.4-beta1 is available on the beta channel to resolve this issue.

Release Notes:
v3.0.4-beta1 - 11/13/2024
Fixes:
- Fixed an issue that would add erroneous CNAME values into a policy domain list when dig was being used to lookup CNAMES.

**Comment by Gundabadec** [comment]
Before:
```
*.twimg.comou
*.twitter.com
*.x.com
ou
twitter.com
x.com
```
If I try to remove `ou` from cli, then it remove

After:
```
*.twitter.com
*.x.com
twitter.com
x.com
```
_don't know why ***.twimg.comou** removed too_
But `ou` still appears randomly.

**Comment by Ranger802004** [comment]
3.0.4 uses the +short flag with dig with it should only output the replies only.

**Comment by Ranger802004** [comment]
After some additional testing on this issue I found some more issues that were causing erroneous entries from CNAME coming in from the dig output.  I have published v3.0.4-beta2 to the beta update channel to address these.  Please test with this version and report any issues you experience.

Release Notes:
v3.0.4-beta2 - 11/19/2024
Fixes:
- Fixed an issue that would add erroneous CNAME values into a policy domain list when dig was being used to lookup CNAMES.
- Fixed an issue when using the deleteip function to delete an IP address.
